language: ruby

script: rspec spec

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ffmpeg
  - gem update bundler

addons:
  code_climate:
    repo_token: e319ec7d18fb8e1f05b460c3ef8fac58af3844d7bfa3d44de6b82eb874bb3e31

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.1
  - rbx-2
  - ruby-head
  - jruby-head
