language: ruby

script: rspec spec

sudo: false

addons:
  apt:
    packages:
    - ffmpeg

addons:
  code_climate:
    repo_token: e319ec7d18fb8e1f05b460c3ef8fac58af3844d7bfa3d44de6b82eb874bb3e31

rvm:
  - 2.0.0-p647
  - 2.1.7
  - 2.2.3
  - rbx-2
  - ruby-head
  - jruby-head
